# Generated by Django 5.1.1 on 2024-12-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='detected_at',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='name',
        ),
        migrations.AddField(
            model_name='flower',
            name='description',
            field=models.TextField(default='No description available'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flower',
            name='image_name',
            field=models.CharField(default='unknown_image.jpg', max_length=255),
            preserve_default=False,
        ),
    ]
